CREATE TABLE IF NOT EXISTS users (
id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
external_id BIGINT DEFAULT NULL,
first_name VARCHAR(255) DEFAULT NULL,
last_name VARCHAR(255) DEFAULT NULL,
PRIMARY KEY (id)
);
