INSERT INTO chat_histories (user_id, user_message, bot_response, date_time)
VALUES
    (1, 'Hey there! How''s your day going? Anything interesting happening?',
     'Hello! My day is going well. Thanks for asking. Any exciting news on your end?',
     '2023-01-01 10:05:00'),
    (2, 'Good day! Checking in to see how you''re doing. Share your thoughts!',
     'Greetings! I''m here and ready to chat. Anything on your mind?',
     '2023-01-01 10:20:00'),
    (3, 'It''s been a while! Ready for a quick chat before you go? Goodbye!',
     'Absolutely! Let''s make the most of our chat. Take care and goodbye!',
     '2023-01-01 10:35:00'),
    (4, 'Time for a new conversation! How''s everything on your end today?',
     'I''m at your service! Let me know if there''s anything specific you''d like to discuss.',
     '2023-01-01 11:05:00'),
    (5, 'Sending positive vibes your way! Enjoying our talks?',
     'Always a pleasure! I value our conversations. Any interesting updates in your life?',
     '2023-01-01 11:20:00'),
    (1, 'Bringing more positivity! What''s on your mind this time?',
     'Feel free to share your thoughts or anything you''d like to discuss. I''m here for you.',
     '2023-01-01 11:35:00'),
    (2, 'Let''s keep the conversation flowing! What''s the highlight of your day?',
     'Ready for anything you want to talk about! Casual chat or deep discussion, it''s your call.',
     '2023-01-01 12:05:00'),
    (3, 'Almost done chatting. Any specific topic you''d like to touch on?',
     'We covered a lot today! If there''s more on your mind or any questions, let me know. I''m here for you.',
     '2023-01-01 12:20:00'),
    (4, 'Final message for today. It''s been great chatting with you!',
     'Thank you for the conversation! If you ever want to continue or discuss something else, feel free to reach out. Take care!',
     '2023-01-01 12:35:00'),
    (5, 'Last message! Wishing you a fantastic day ahead!',
     'Thank you! Wishing you an amazing day too. If you ever want to chat again, I''ll be here. Take care and goodbye for now!',
     '2023-01-01 13:05:00'),
    (1, 'Hello John! How has your day been so far? I hope everything is going well for you.',
     'Hi there! I''m doing great, thank you for asking. Anything exciting happening on your end?',
     '2023-01-01 10:00:00'),
    (2, 'Hey! I''m just checking in. How are things going for you? Let me know if there''s anything on your mind.',
     'I am doing well, thank you! It''s always nice to chat with you. Anything specific you''d like to talk about?',
     '2023-01-01 10:15:00'),
    (3, 'It was nice talking to you, but I have to go now. Goodbye!',
     'See you later! Take care and feel free to reach out whenever you want to chat. Have a great day!',
     '2023-01-01 10:30:00'),
    (4,'Another day, another conversation. How are you doing?',
     'I''m here and ready to chat! Let me know if there''s anything specific you''d like to discuss or if you just want to say hi.',
     '2023-01-01 11:00:00'),
    (5,  'Yet another message from me. Hope you''re enjoying our conversations!',
     'Of course! I always enjoy our conversations. It''s great to have someone to chat with. Anything new happening in your life?',
     '2023-01-01 11:15:00'),
    (1, 'More messages coming your way! Anything specific on your mind today?',
     'Feel free to share your thoughts or anything you''d like to discuss. I''m here to chat and provide support if needed.',
     '2023-01-01 11:30:00'),
    (2, 'Keep the conversation going! What''s the latest in your world?',
     'I''m here and ready to respond. Whether it''s a casual chat or something more serious, feel free to share. Your thoughts matter!',
     '2023-01-01 12:00:00'),
    (3, 'Almost done with the messages. Anything you''d like to talk about before we wrap up?',
     'We''ve covered quite a bit today! If there''s anything else on your mind or if you have questions, let me know. I''m here for you.',
     '2023-01-01 12:15:00'),
    (4, 'Last one from me today. It''s been a pleasure chatting with you!',
     'Thank you for the conversation! If you ever want to continue our chat or if there''s anything else you''d like to discuss, feel free to reach out. Take care!',
     '2023-01-01 12:30:00'),
    (5, 'Closing message. Have a fantastic day ahead!',
     'Thank you! Wishing you a fantastic day too. If you ever want to chat again, I''ll be here. Take care and goodbye for now!',
     '2023-01-01 13:00:00'),
    (1, 'Hello John! How has your day been so far? I hope everything is going well for you.',
     'Hi there! I''m doing great, thank you for asking. Anything exciting happening on your end?',
     '2023-01-01 10:00:00'),
    (2, 'Hey! I''m just checking in. How are things going for you? Let me know if there''s anything on your mind.',
     'I am doing well, thank you! It''s always nice to chat with you. Anything specific you''d like to talk about?',
     '2023-01-01 10:15:00'),
    (3, 'It was nice talking to you, but I have to go now. Goodbye!',
     'See you later! Take care and feel free to reach out whenever you want to chat. Have a great day!',
     '2023-01-01 10:30:00'),
    (4,'Another day, another conversation. How are you doing?',
     'I''m here and ready to chat! Let me know if there''s anything specific you''d like to discuss or if you just want to say hi.',
     '2023-01-01 11:00:00'),
    (5,  'Yet another message from me. Hope you''re enjoying our conversations!',
     'Of course! I always enjoy our conversations. It''s great to have someone to chat with. Anything new happening in your life?',
     '2023-01-01 11:15:00'),
    (1, 'More messages coming your way! Anything specific on your mind today?',
     'Feel free to share your thoughts or anything you''d like to discuss. I''m here to chat and provide support if needed.',
     '2023-01-01 11:30:00'),
    (2, 'Keep the conversation going! What''s the latest in your world?',
     'I''m here and ready to respond. Whether it''s a casual chat or something more serious, feel free to share. Your thoughts matter!',
     '2023-01-01 12:00:00'),
    (3, 'Almost done with the messages. Anything you''d like to talk about before we wrap up?',
     'We''ve covered quite a bit today! If there''s anything else on your mind or if you have questions, let me know. I''m here for you.',
     '2023-01-01 12:15:00'),
    (4, 'Last one from me today. It''s been a pleasure chatting with you!',
     'Thank you for the conversation! If you ever want to continue our chat or if there''s anything else you''d like to discuss, feel free to reach out. Take care!',
     '2023-01-01 12:30:00'),
    (5, 'Closing message. Have a fantastic day ahead!',
     'Thank you! Wishing you a fantastic day too. If you ever want to chat again, I''ll be here. Take care and goodbye for now!',
     '2023-01-01 13:00:00'),
    (1, 'Hello John! How has your day been so far? I hope everything is going well for you.',
     'Hi there! I''m doing great, thank you for asking. Anything exciting happening on your end?',
     '2023-01-01 10:00:00'),
    (2, 'Hey! I''m just checking in. How are things going for you? Let me know if there''s anything on your mind.',
     'I am doing well, thank you! It''s always nice to chat with you. Anything specific you''d like to talk about?',
     '2023-01-01 10:15:00'),
    (3, 'It was nice talking to you, but I have to go now. Goodbye!',
     'See you later! Take care and feel free to reach out whenever you want to chat. Have a great day!',
     '2023-01-01 10:30:00'),
    (4,'Another day, another conversation. How are you doing?',
     'I''m here and ready to chat! Let me know if there''s anything specific you''d like to discuss or if you just want to say hi.',
     '2023-01-01 11:00:00'),
    (5,  'Yet another message from me. Hope you''re enjoying our conversations!',
     'Of course! I always enjoy our conversations. It''s great to have someone to chat with. Anything new happening in your life?',
     '2023-01-01 11:15:00'),
    (1, 'More messages coming your way! Anything specific on your mind today?',
     'Feel free to share your thoughts or anything you''d like to discuss. I''m here to chat and provide support if needed.',
     '2023-01-01 11:30:00'),
    (2, 'Keep the conversation going! What''s the latest in your world?',
     'I''m here and ready to respond. Whether it''s a casual chat or something more serious, feel free to share. Your thoughts matter!',
     '2023-01-01 12:00:00'),
    (3, 'Almost done with the messages. Anything you''d like to talk about before we wrap up?',
     'We''ve covered quite a bit today! If there''s anything else on your mind or if you have questions, let me know. I''m here for you.',
     '2023-01-01 12:15:00'),
    (4, 'Last one from me today. It''s been a pleasure chatting with you!',
     'Thank you for the conversation! If you ever want to continue our chat or if there''s anything else you''d like to discuss, feel free to reach out. Take care!',
     '2023-01-01 12:30:00'),
    (5, 'Closing message. Have a fantastic day ahead!',
     'Thank you! Wishing you a fantastic day too. If you ever want to chat again, I''ll be here. Take care and goodbye for now!',
     '2023-01-01 13:00:00'),
    (1, 'Hello John! How has your day been so far? I hope everything is going well for you.',
     'Hi there! I''m doing great, thank you for asking. Anything exciting happening on your end?',
     '2023-01-01 10:00:00'),
    (2, 'Hey! I''m just checking in. How are things going for you? Let me know if there''s anything on your mind.',
     'I am doing well, thank you! It''s always nice to chat with you. Anything specific you''d like to talk about?',
     '2023-01-01 10:15:00'),
    (3, 'It was nice talking to you, but I have to go now. Goodbye!',
     'See you later! Take care and feel free to reach out whenever you want to chat. Have a great day!',
     '2023-01-01 10:30:00'),
    (4,'Another day, another conversation. How are you doing?',
     'I''m here and ready to chat! Let me know if there''s anything specific you''d like to discuss or if you just want to say hi.',
     '2023-01-01 11:00:00'),
    (5,  'Yet another message from me. Hope you''re enjoying our conversations!',
     'Of course! I always enjoy our conversations. It''s great to have someone to chat with. Anything new happening in your life?',
     '2023-01-01 11:15:00'),
    (1, 'More messages coming your way! Anything specific on your mind today?',
     'Feel free to share your thoughts or anything you''d like to discuss. I''m here to chat and provide support if needed.',
     '2023-01-01 11:30:00'),
    (2, 'Keep the conversation going! What''s the latest in your world?',
     'I''m here and ready to respond. Whether it''s a casual chat or something more serious, feel free to share. Your thoughts matter!',
     '2023-01-01 12:00:00'),
    (3, 'Almost done with the messages. Anything you''d like to talk about before we wrap up?',
     'We''ve covered quite a bit today! If there''s anything else on your mind or if you have questions, let me know. I''m here for you.',
     '2023-01-01 12:15:00'),
    (4, 'Last one from me today. It''s been a pleasure chatting with you!',
     'Thank you for the conversation! If you ever want to continue our chat or if there''s anything else you''d like to discuss, feel free to reach out. Take care!',
     '2023-01-01 12:30:00'),
    (5, 'Closing message. Have a fantastic day ahead!',
     'Thank you! Wishing you a fantastic day too. If you ever want to chat again, I''ll be here. Take care and goodbye for now!',
     '2023-01-01 13:00:00');
